# Copyright (c) 2026 RobotX. All rights reserved.
# Author: Jiqian Zhao <zhaojq2003@163.com>
# Date: 2026-06-27

"""编译扩展 `_mfac_core` 的类型存根."""

class CFDLController:
    def __init__(
        self,
        *,
        eta: float = 1.0,
        mu: float = 1.0,
        rho: float = 0.1,
        lambda_: float = 0.02,
        eps: float = 1e-5,
        l_y: int = 0,
        l_u: int = 1,
        initial_phi: float = 0.5,
        u0: float = 0.0,
        u_min: float | None = None,
        u_max: float | None = None,
    ) -> None: ...
    def update(self, y: float, yd: float) -> tuple[float, float, float, float, float]: ...
    def reset(self) -> None: ...
    def get_phi(self) -> list[float]: ...
    def set_phi_hat(self, phi: list[float]) -> None: ...


class PFDLController:
    def __init__(
        self,
        *,
        eta: float = 1.0,
        mu: float = 1.0,
        rho: float = 0.1,
        lambda_: float = 0.02,
        eps: float = 1e-5,
        l_y: int = 0,
        l_u: int = 2,
        initial_phi: float = 0.5,
        u0: float = 0.0,
        u_min: float | None = None,
        u_max: float | None = None,
    ) -> None: ...
    def update(self, y: float, yd: float) -> float: ...
    def update_logged(self, y: float, yd: float) -> tuple[float, float, list[float], float, list[float]]: ...
    def reset(self) -> None: ...
    def get_phi(self) -> list[float]: ...
    def set_phi_hat(self, phi: list[float]) -> None: ...


class FFDLController:
    def __init__(
        self,
        *,
        eta: float = 1.0,
        mu: float = 1.0,
        rho: float = 0.1,
        lambda_: float = 0.02,
        eps: float = 1e-5,
        l_y: int = 1,
        l_u: int = 2,
        initial_phi: float = 0.5,
        u0: float = 0.0,
        u_min: float | None = None,
        u_max: float | None = None,
    ) -> None: ...
    def update(self, y: float, yd: float) -> float: ...
    def update_logged(self, y: float, yd: float) -> tuple[float, float, list[float], float, list[float]]: ...
    def reset(self) -> None: ...
    def get_phi(self) -> list[float]: ...
    def set_phi_hat(self, phi: list[float]) -> None: ...
    def set_rho_vector(self, rho: list[float]) -> None: ...


def pid_to_pfdl(kp: float, ti: float, td: float, ts: float, order: int = 3) -> list[float]: ...
def zn_response_to_pfdl(k: float, tau: float, time_delay: float, ts: float, order: int = 3) -> list[float]: ...
def critical_proportional_to_pfdl(ku: float, tu: float, ts: float, order: int = 3) -> list[float]: ...
def apply_pfdl_initial_guess(controller: PFDLController, psi: list[float]) -> None: ...
def ffdl_zn_tuning(controller: FFDLController, k: float, tau: float, time_delay: float, ts: float) -> list[float]: ...
def apply_ffdl_zn_tuning(controller: FFDLController, k: float, tau: float, time_delay: float, ts: float) -> None: ...
def ffdl_critical_tuning(controller: FFDLController, ku: float, tu: float, ts: float) -> list[float]: ...
def apply_ffdl_critical_tuning(controller: FFDLController, ku: float, tu: float, ts: float) -> None: ...
